### PR TITLE
PR #35: Implementation for issue #88

### LINKED ISSUE #88: Experiment Setup
Prepare 2 different configurations for experiment setup:
1. Run Random and OpO with a single mutator - Speed Mutator
2. Run Random and OpO with multiple mutators - Speed and Initial Point Mutators

### PR DESCRIPTION
**Pull request by harveyvn**
Prepare two different configurations for the experiment :
- Run Random and OpO with a single mutator - Speed Mutator
- Run Random and OpO with multiple mutators - Speed and Initial Point Mutator

Add some plots to demonstrate the result. 

Separating all constants to a constant class - [link](https://github.com/TriHuynh00/AC3R-Demo/pull/90/files?authenticity_token=ruUJOt%2FO3XDXMisi6gfV607ttu6rn%2F%2BeJm7LH9YVpFsr6JGhJL5WUhAs0Vya7Vh5ZZZlBHiC5M0jyDFRZZTu3Q%3D%3D&file-filters%5B%5D=.py&hide-deleted-files=true#diff-7bcb79a90acb551863861427cf9b71329068a34c37e599da425eafd03340f431). 

Here you can find some properties of Case 5 in the comments below, and I also attached the Review PR's link with file filtering that can ease your review. [Pull Request Review URL](https://github.com/TriHuynh00/AC3R-Demo/pull/90/files?authenticity_token=W5DBDRO%2BG7vRngXKJ0MkWr7D9zo%2FlnlQogH%2BJxZ0s2renVmW6M6QmRaA%2F7RXqanIlbgk0OyLYgOnpwRppfX57A%3D%3D&file-filters%5B%5D=.py)

### CODE REVIEW

**Comment by harveyvn** [comment]
Plot of Single Random and OpO, Multiple Random and OpO

Multiple

**Comment by harveyvn** [comment]
Plot including confidence interval of the curve

CI

**Comment by harveyvn** [comment]
Box plot for all algorithms

BoxPlot

**Review by alessiogambi — APPROVED** [review]
LGTM

**Pull request merged**
